import Head from 'next/head';
import Hero from '@/components/pages/HomePage/Hero/Hero';
import Features from '@/components/pages/HomePage/Features/Features';
import Reviews from '@/components/pages/HomePage/Reviews/Reviews';
import Articles from '@/components/pages/HomePage/Articles/Articles';
import Footer from '@/components/fragments/Footer/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <Features />
        <Reviews />
        <Articles />
        <Footer />
      </main>
    </div>
  );
}
